name: Overdrive
main: io.github.bananapuncher714.overdrive.Overdrive
version: Lunatic
description: WARNING X WARNING X WARNING
author: BananaPuncher714
website: aaaaahhhhh.com
commands:
  overdrive:
    description: Easy mode?!? Only elementary school kids play in easy mode.
    permission: overdrive.lunatic

permissions:
  overdrive.lunatic:
    default: op